// MadSysPlug.js for ModernActiveDesktop
// Made by Ingan121
// Licensed under the MIT License
// SPDX-License-Identifier: MIT

'use strict';

// This script handles all the communication between MAD and the system plugin

(function() {
    window.madSysPlug = {
        checkConnectivity,
        getSystemScheme,
        openExternal,
        saveFile,
        mediaControl,
        beginInput,
        focusInput,
        endInput,
        getClipboard,
        spotifyLogin,
        inputStatus: false
    };

    let eventSource;
    let waitingForBeginInput = false;
    let token = top.spToken || null;

    // Fetch the token generated by the system plugin (WPE only)
    async function fetchToken() {
        const url = new URL("madsp-token.txt", top.location.href).href;
        token = (await fetch(url).then(res => res.text())).split("\r\n")[0];
        window.spToken = token;
    }

    // Send a request to the system plugin
    async function request(endpoint, data, headers = {}, rawReturn) {
        if (endpoint !== "connecttest" && !localStorage.sysplugIntegration) {
            return;
        }

        if (!token && (top.runningMode || 0) === 1) {
            try {
                await fetchToken();
            } catch (error) {
                console.error("Failed to get the token; continuing without it", error);
            }
        }
        if (token) {
            headers["X-MADSP-Token"] = token;
        }
        if (data) {
            if (typeof data !== "string" && !(data instanceof FormData) && !(data instanceof Blob)) {
                data = JSON.stringify(data);
                headers["Content-Type"] = "application/json";
            }

            return await fetch(`http://localhost:3031/${endpoint}`, {
                method: "POST", headers, body: data
            }).then(res => rawReturn ? res : res.text());
        } else {
            return await fetch(`http://localhost:3031/${endpoint}`, {
                headers
            }).then(res => rawReturn ? res : res.text());
        }
    }

    // Check if the system plugin is running and up to date
    async function checkConnectivity() {
        try {
            const response = await request("connecttest");
            if (response === "403 Forbidden") {
                // The system plugin has denied the connection
                return -2;
            } else {
                switch (top.madVersion.compare(response, true)) {
                    case 1:
                        // The system plugin is outdated
                        return -1;
                    case -1:
                        // The system plugin is newer than MAD
                        return -3;
                    default:
                        // The system plugin is up to date
                        return 1;
                }
            }
        } catch (error) {
            // The system plugin is not running or something went wrong
            return 0;
        }
    }

    // Get the system color scheme in MAD-compatible CSS variables
    async function getSystemScheme() {
        return await request("systemscheme");
    }

    // Open a URL in the default browser (or the deprecated SysPlug ChannelViewer)
    async function openExternal(url, headers) {
        return await request("open", url, headers);
    }

    // Save a file to the system
    // Returns a raw fetch response. Use .text() to get the filename
    // Text return: Filename if successful, "Aborted" if canceled
    async function saveFile(data, headers) {
        // data: FormData or Blob
        // headers: {
        //    "X-Format-Name": "File format description",
        //    "X-Format-Extension": "File extension",
        //    "X-File-Name": "Default file sname",
        //    "X-File-Path": "Default file path, specify as Electron's app.getPath()",
        // }
        return await request("save", data, headers, true);
    }

    // Control the media player
    // Action: "play", "pause", "playpause", "stop", "next", "prev" (See MediaControlCLI.exe help)
    async function mediaControl(action, title = "") {
        return await request(action, title);
    }

    // Begin MadInput
    // noTimeout: Prevent the system plugin from closing the input panel when its inactive for 30 seconds
    // (meant for madPrompt where the timeout causes the dialog to be closed)
    // Return: true if successful, false if failed
    async function beginInput(noTimeout) {
        if (madSysPlug.inputStatus || waitingForBeginInput) {
            return false;
        }

        try {
            waitingForBeginInput = true; // Prevent multiple beginInput calls
            const headers = noTimeout ? { "X-No-Timeout": "true" } : {};
            const response = await request("begininput", null, headers);
            waitingForBeginInput = false;
            if (response !== "OK") {
                return false;
            } else {
                numInputPrep();
            }
        } catch (error) {
            waitingForBeginInput = false;
            return false;
        }

        madSysPlug.inputStatus = true;
        getInput();
        return true;
    }

    // Get input from the system plugin
    // Long polling from /getinput
    async function getInput() {
        const inputEvent = new Event("madinput");
        while (madSysPlug.inputStatus) {
            await new Promise(resolve => {
                eventSource = new EventSource("http://localhost:3031/getinput");
                eventSource.onmessage = function(event) {
                    inputEvent.key = event.data;
                    document.dispatchEvent(inputEvent);
                    if (event.data === "Escape") {
                        madSysPlug.inputStatus = false;
                    }
                    eventSource.close();
                    resolve();
                };
                eventSource.onerror = function (error) {
                    console.error("EventSource failed:", error);
                    endInput(true);
                    resolve();
                };
            });
        }
    }

    // Focus the input panel
    function focusInput(noTimeout) {
        if (!localStorage.sysplugIntegration) {
            return;
        }
        if (!madSysPlug.inputStatus) {
            beginInput(noTimeout);
            return;
        }
        setTimeout(() => {
            // Wait a bit cuz wallpaper click un-focuses the input panel
            request("focusinput");
            numInputPrep();
        }, 100);
    }

    // End MadInput
    // abrupt: End the input without sending a request
    // Return: "OK" if successful, -1 if abrupt
    async function endInput(abrupt = false) {
        if (abrupt) {
            madSysPlug.inputStatus = false;
            if (eventSource) {
                eventSource.close();
            }
            return -1;
        }
        const response = await request("endinput");
        if (response === "OK") {
            madSysPlug.inputStatus = false;
            if (eventSource) {
                eventSource.close();
            }
        }
        return response;
    }

    // Get the clipboard content
    async function getClipboard() {
        return await request("clipboard") || "";
    }

    // Open the Spotify login page and get the authorization token and the code verifier
    // https://developer.spotify.com/documentation/web-api/tutorials/code-pkce-flow
    // Returns: { code, verifier, clientId } if successful
    // Continue getting the access token with the returned values
    // Returns { error: "error message" } if failed
    async function spotifyLogin() {
        if (!localStorage.sysplugIntegration) {
            return;
        }
        const response = await request("spotify/auth", null, {}, true);
        if (response.headers.get("Content-Type") !== "application/json") {
            if (response.status === 403) {
                return { error: "System plugin has denied the connection" };
            }
            return { error: "Invalid response" };
        }
        return await response.json();
    }

    // input[type="number"] doesn't work well with MadInput, so we need to convert it to text
    function numInputPrep() {
        const textbox = document.activeElement;
        if (textbox.tagName === "INPUT") {
            if (textbox.type === "number") {
                textbox.type = "text";
                textbox.dataset.origType = "number";
                textbox.addEventListener("blur", () => {
                    textbox.type = "number";
                    delete textbox.dataset.origType;
                }, { once: true });
            }
            textbox.addEventListener("blur", () => {   
                const changeEvent = new Event("change");
                textbox.dispatchEvent(changeEvent);
            }, { once: true });
        }
    }

    window.addEventListener("beforeunload", () => {
        if (madSysPlug.inputStatus) {
            endInput();
        }
    });

    window.addEventListener("message", (event) => {
        if (event.data.type === "sysplug-option-changed") {
            if (!localStorage.sysplugIntegration && madSysPlug.inputStatus) {
                endInput(true);
            }
        }
    });
})();